sudo: false
language: node_js
node_js:
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5"
  - "6"
  - "iojs"

cache:
  directories:
    - node_modules

install:
  - npm install --production

script:
  - npm run build
