sudo: false
language: node_js
node_js:
  - "4"
  - "6"

branches:
  only:
    - master
    - webpack2

cache:
  directories:
    - node_modules

install:
  - npm install -g npm
  - node --version
  - npm --version
  - npm install --production

script:
  - npm run eslint
