version: "{build}"

environment:
  matrix:
    - nodejs_version: "6"

matrix:
  fast_finish: true

build: off

install:
  # Install Node.js
  #- ps: Install-Product node $env:nodejs_version

  # Upgrade npm
  - npm install -g npm

test_script:
  # Output our current versions for debugging
  - node --version
  - npm --version
  - npm install
  - npm test
